import Head from "next/head";
import "@bjodol/natura/styles.css";
import { useRouter } from "next/router";
import { NavLink } from "../components/NavLink";
import { Fragment } from "react";

const routes = [
  {
    title: "Style",
    elements: ["/typography"],
  },
  {
    title: "Components",
    elements: ["/buttons", "/links", "/hex", "/tiles", "/controls"],
  },
  {
    title: "Layouts",
    elements: ["/hex-grid"],
  },
];

const App = ({ Component, pageProps }) => {
  const { pathname } = useRouter();
  return (
    <>
      <Head>
        <title>Natura UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="fixed bg-base-main text-base-main-contrast w-[288px] h-screen bg-opacity-80 border-base-hover">
        <nav>
          {routes.map(({ elements, title }) => (
            <Fragment key={title}>
              <h2 className="pl-4 pt-8 label">{title}</h2>
              <ul>
                {elements.map((href) => (
                  <li key={href}>
                    <NavLink
                      href={href}
                      className="link-nav link-nav-primary capitalize"
                      pathname={pathname}
                    >
                      {href.split("/").join(" ").trim()}
                    </NavLink>
                  </li>
                ))}
              </ul>
            </Fragment>
          ))}
        </nav>
      </header>
      <main className="ml-[288px] p-12">
        <Component {...pageProps} />
      </main>
    </>
  );
};

export default App;
