import Head from "next/head";
import Link from "next/link";
import "@bjodol/natura/styles.css";

const App = ({ Component, pageProps }) => (
  <>
    <Head>
      <title>Natura UI</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <header className="fixed bg-base-main text-base-main-contrast border-b border-base-active w-[288px] h-screen bg-opacity-80 border-r-2 border-base-hover">
      <nav>
        <h2 className="pl-4 pt-4">Components</h2>
        <ul>
          <li>
            <Link href="/typography">
              <a className="link link-primary hover:scale-100 hover:pl-8">
                Typography
              </a>
            </Link>
          </li>
          <li>
            <Link href="/buttons">
              <a className="link link-primary hover:scale-100 hover:pl-8">
                Buttons
              </a>
            </Link>
          </li>
          <li>
            <Link href="/links">
              <a className="link link-primary hover:scale-100 hover:pl-8">
                Links
              </a>
            </Link>
          </li>
          <li>
            <Link href="/hex">
              <a className="link link-primary hover:scale-100 hover:pl-8">
                Hex
              </a>
            </Link>
          </li>
          <li>
            <Link href="/hex-grid">
              <a className="link link-primary hover:scale-100 hover:pl-8">
                Hex grid
              </a>
            </Link>
          </li>
        </ul>
      </nav>
    </header>
    <main className="ml-[288px] p-12">
      <Component {...pageProps} />
    </main>
  </>
);

export default App;
