import Head from "next/head";

const COLOR_SCHEMES = {
  PRIMARY: "control control-primary",
  SECONDARY: "control control-secondary",
  BASE: "control control-base",
  WARNING: "control control-warning",
  DANGER: "control control-danger",
  TRANSPARENT: "control control-transparent",
};

const CONTROL_TYPES = {
  TEXT: "text",
  NUMBER: "number",
  EMAIL: "email",
  TEL: "tel",
  URL: "url",
  HIDDEN: "hidden",
  RANGE: "range",
  SEARCH: "search",
};

export default function Controls() {
  return (
    <div>
      <Head>
        <title>Controls - Natura design system</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="h1 mb-4">Controls</h1>
      <div className="grid gap-4 sm:grid-cols-4">
        <h2 className="h2 sm:col-span-4">Input with label</h2>
        {Object.values(COLOR_SCHEMES).map((color) => (
          <label className={color} key={color}>
            {color}
            <input placeholder={color} type="text" className="w-full" />
          </label>
        ))}
        <h2 className="h2 sm:col-span-4">Input types</h2>
        {Object.values(CONTROL_TYPES).map((color) => (
          <label className="control control-base" key={color}>
            {color}
            <input placeholder={color} type={color} className="w-full" />
          </label>
        ))}
        <label className={`control control-base w-full`}>
          disabled
          <input
            placeholder="disabled"
            type="text"
            disabled
            className={`control control-base w-full`}
          />
        </label>
        <label className="control control-base">
          select
          <select className="w-full">
            <option value={0}>select</option>
            <option value={1}>not select</option>
          </select>
        </label>
        <label className="control control-base sm:col-span-2">
          textarea
          <textarea className="w-full" />
        </label>
        <label className={`control control-base w-full`}>
          checkbox
          <input type="checkbox" className="" />
        </label>
      </div>
    </div>
  );
}
