import Head from "next/head";

const COLOR_SCHEMES = {
  PRIMARY: "hex-primary",
  SECONDARY: "hex-secondary",
  BASE: "hex-base",
  WARNING: "hex-warning",
  DANGER: "hex-danger",
  TRANSPARENT: "hex-transparent",
};

export default function Buttons() {
  return (
    <div>
      <Head>
        <title>Hex grid - interactive Natura design system</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hexagon grid</h1>
      <h2>Default</h2>
      <div className="hex-container">
        <div className="hex-grid">
          {Object.values(COLOR_SCHEMES).map((color) => (
            <button
              key={color}
              className={`hex ${color} interactive`}
            >{`${color}`}</button>
          ))}
          {Object.values(COLOR_SCHEMES).map((color) => (
            <div key={color} className={`hex ${color}`}>
              {color}
            </div>
          ))}
        </div>
      </div>
      <h2 className="h-12">Spacing and gap</h2>
      <div className="hex-container">
        <div className="hex-grid hex-grid-16 hex-grid-gap-px">
          {Object.values(COLOR_SCHEMES).map((color) => (
            <button
              key={color}
              className={`hex ${color} interactive`}
            >{`hex`}</button>
          ))}
          {Object.values(COLOR_SCHEMES).map((color) => (
            <div key={color} className={`hex ${color}`}>{`hex`}</div>
          ))}
        </div>
      </div>

      <footer></footer>
    </div>
  );
}
