import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-base-main text-base-main-contrast h-screen">
        <button className="btn btn-transparent">Button</button>
        <button className="btn btn-primary">Button</button>
        <button className="btn btn-secondary">Button</button>
        <button className="btn btn-base">Button</button>
        <button className="btn btn-warning">Button</button>
        <button className="btn btn-danger">Button</button>
      </main>

      <footer></footer>
    </div>
  );
}
