import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="fixed bg-base-main text-base-main-contrast border-b border-base-active w-[288px] h-screen bg-opacity-80 border-r-2 border-base-hover">
        <nav>
          <h2 className="pl-4 pt-4">Components</h2>
          <ul>
            <li>
              <Link href="/buttons">
                <a className="link link-primary hover:scale-100 hover:pl-8">
                  Buttons
                </a>
              </Link>
            </li>
            <li>
              <Link href="/links">
                <a className="link link-primary hover:scale-100 hover:pl-8">
                  Links
                </a>
              </Link>
            </li>
          </ul>
        </nav>
      </header>
      <main className="ml-[288px] p-12">
        <h1>Natura - Raw and clean</h1>
      </main>
    </div>
  );
}
