import Head from "next/head";
import Image from "next/image";

const COLOR_SCHEMES = {
  PRIMARY: "link-primary",
  SECONDARY: "link-secondary",
  BASE: "link-base",
  WARNING: "link-warning",
  DANGER: "link-danger",
  TRANSPARENT: "link-transparent",
};

export default function Links() {
  return (
    <div>
      <Head>
        <title>Links - Natura design system</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 id="top">Links</h1>
      <div className="flex space-x-4 flex-wrap">
        {Object.values(COLOR_SCHEMES).map((color) => (
          <a
            href="#top"
            key={color}
            className={`link ${color}`}
          >{`${color}`}</a>
        ))}
      </div>
      <div className="flex space-x-4 flex-wrap">
        {Object.values(COLOR_SCHEMES).map((color) => (
          <a
            href="#top"
            key={color}
            className={`link ${color} link-inline`}
          >{`${color}`}</a>
        ))}
      </div>
    </div>
  );
}
